name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
          RUNNER_NUMBER: ${{ github.run_number }}
          REPO_NAME: ${{ github.repository }}
        run: |
          IMAGE_TAG=${BRANCH_NAME}-${COMMIT_HASH::6}-${RUNNER_NUMBER}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${REPO_NAME}:${IMAGE_TAG} .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker image
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
          RUNNER_NUMBER: ${{ github.run_number }}
          REPO_NAME: ${{ github.repository }}
        run: |
          IMAGE_TAG=${BRANCH_NAME}-${COMMIT_HASH::6}-${RUNNER_NUMBER}
          docker push ${{ secrets.DOCKER_USERNAME }}/${REPO_NAME}:${IMAGE_TAG}